apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawfiq-regapp
  labels:
     app: tawfiq

spec:
  replicas: 2
  selector:
    matchLabels:
      app: tawfiq

  template:
    metadata:
      labels:
        app: tawfiq
    spec:
      containers:
      - name: tawfiq15
        image: selimhorri/employee-simple-management
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    
