version: 2.1

jobs:
  build:
    docker:
      - image: tawfiq15/centos_ssh
    steps:
      - checkout
      - run: yum -y install maven -y
      - save_cache:
          key: "maven-packages"
          paths:
            - /src/node_modules
      - run: maven build 
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "maven-packages"
      - run: maven --version
       


workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      